import datetime
import google_auth_oauthlib.flow
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from calendar_sync.models import GoogleOAuthToken
from common.utils import log_request_event

CLIENT_CONFIG = {
    "web": {
        "client_id": settings.GOOGLE_CLIENT_ID,
        "client_secret": settings.GOOGLE_CLIENT_SECRET,
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "redirect_uris": [settings.GOOGLE_REDIRECT_URI],
    }
}

@login_required
def google_oauth_redirect_view(request):
    """
    Redirects user to Google OAuth page.
    """
    if not settings.GOOGLE_CLIENT_ID or not settings.GOOGLE_CLIENT_SECRET or not settings.GOOGLE_REDIRECT_URI:
        messages.error(request, "Google OAuth is not configured on this server.")
        return redirect('dashboard')

    flow = google_auth_oauthlib.flow.Flow.from_client_config(
        CLIENT_CONFIG,
        scopes=['https://www.googleapis.com/auth/calendar']
    )
    flow.redirect_uri = settings.GOOGLE_REDIRECT_URI
    
    authorization_url, state = flow.authorization_url(
        access_type='offline',
        include_granted_scopes='true',
        prompt='consent'
    )
    request.session['oauth_state'] = state
    
    # Save the PKCE code_verifier generated by Flow to retrieve in the callback
    if hasattr(flow, 'code_verifier') and isinstance(flow.code_verifier, str):
        request.session['oauth_code_verifier'] = flow.code_verifier
        
    request.session.save()
    return redirect(authorization_url)


@login_required
def google_oauth_callback_view(request):
    """
    Exchanges authorization code for access and refresh tokens.
    """
    state = request.session.get('oauth_state')
    if not state:
        messages.error(request, "OAuth state parameter missing from session.")
        return redirect('dashboard')

    flow = google_auth_oauthlib.flow.Flow.from_client_config(
        CLIENT_CONFIG,
        scopes=['https://www.googleapis.com/auth/calendar'],
        state=state
    )
    flow.redirect_uri = settings.GOOGLE_REDIRECT_URI

    # Restore the PKCE code_verifier generated during the redirect view
    code_verifier = request.session.get('oauth_code_verifier')
    if code_verifier:
        flow.code_verifier = code_verifier

    try:
        # Resolve request URL and fetch tokens
        flow.fetch_token(authorization_response=request.build_absolute_uri())
        credentials = flow.credentials

        expiry = credentials.expiry
        if expiry and timezone.is_naive(expiry):
            expiry = timezone.make_aware(expiry)

        token_record, created = GoogleOAuthToken.objects.update_or_create(
            user=request.user,
            defaults={
                'access_token': credentials.token,
                'refresh_token': credentials.refresh_token or '',
                'token_expiry': expiry or (timezone.now() + datetime.timedelta(seconds=credentials.expires_in))
            }
        )

        log_request_event(
            request=request,
            action="GOOGLE_CALENDAR_CONNECTED",
            details={"token_id": token_record.id, "user_id": str(request.user.id)}
        )

        messages.success(request, "Successfully connected to Google Calendar!")
    except Exception as e:
        messages.error(request, f"Google OAuth exchange failed: {str(e)}")

    return redirect('dashboard')

