# Generated by Django 5.2.15 on 2026-06-26 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('hospital_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=150)),
                ('gov_id_file', models.FileField(blank=True, null=True, upload_to='doctor_documents/')),
                ('medical_license_file', models.FileField(blank=True, null=True, upload_to='doctor_documents/')),
                ('degree_certificate_file', models.FileField(blank=True, null=True, upload_to='doctor_documents/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
