# Generated by Django 5.2.15 on 2026-06-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_total_reviews_doctorleave_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
