# Generated by Django 5.2.15 on 2026-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MediBridge Medical Center', max_length=150)),
                ('logo', models.FileField(blank=True, null=True, upload_to='hospital_logo/')),
                ('address', models.CharField(default='100 Medical Center Parkway, Suite 400, Aura City', max_length=255)),
                ('phone', models.CharField(default='+1 (555) 019-2831', max_length=50)),
                ('email', models.EmailField(default='contact@medibridge.hospital.local', max_length=254)),
                ('website', models.CharField(default='www.medibridge-clinic.local', max_length=200)),
                ('working_hours', models.CharField(default='Mon - Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 2:00 PM', max_length=255)),
                ('emergency_contact', models.CharField(default='+1 (555) 019-9111', max_length=100)),
            ],
            options={
                'verbose_name': 'Hospital Configuration',
                'verbose_name_plural': 'Hospital Configuration',
            },
        ),
    ]
