"""
Django settings for hms project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from repository root (.env)
load_dotenv(BASE_DIR.parent / '.env')

# Security settings
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+kv4w%6nds^a&og6w^2!w=1!j+id&vu@+**#_i-9f$jx_6ge(*')
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

allowed_hosts_raw = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,web')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_raw.split(',') if host.strip()]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'corsheaders',

    # Modular apps
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'doctors.apps.DoctorsConfig',
    'patients.apps.PatientsConfig',
    'appointments.apps.AppointmentsConfig',
    'medical_records.apps.MedicalRecordsConfig',
    'calendar_sync.apps.CalendarSyncConfig',
    'notifications.apps.NotificationsConfig',
    'admin_panel.apps.AdminPanelConfig',
    'common.apps.CommonConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'common.context_processors.hospital_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'hms.wsgi.application'

# Database
# Connects to Postgres inside Docker compose; falls back to sqlite locally if not configured
DB_HOST = os.getenv('DB_HOST')
if DB_HOST and os.getenv('USE_SQLITE', 'False').lower() != 'true':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'hms_db'),
            'USER': os.getenv('DB_USER', 'hms_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'hms_secure_pass'),
            'HOST': DB_HOST,
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Authentication Override
AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'landing'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Calendar Integration Settings
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI')

# Enable OAUTHLIB_INSECURE_TRANSPORT only in development (DEBUG=True or env var set to 1)
OAUTHLIB_INSECURE_TRANSPORT = os.getenv('OAUTHLIB_INSECURE_TRANSPORT')
if OAUTHLIB_INSECURE_TRANSPORT == '1' or DEBUG:
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'


# Email Service settings
EMAIL_SERVICE_URL = os.getenv('EMAIL_SERVICE_URL')
EMAIL_FROM = os.getenv('EMAIL_FROM', 'noreply@hospital.local')

# CORS Config
CORS_ALLOW_ALL_ORIGINS = True

